### ISSUE TITLE
add bot self introduction

### ISSUE THREAD

**Issue by Sivyer9303** [Koooooo-7/K-Bot#11]
add a plugin to show bot's introduction,i.e. 
`!kono hi`
will get a message like 'hi,i'm kbot, i can talk with u by ur type command....'.
is it necessary?

**Comment by Koooooo-7** [comment]
cool, we can add more bonus also.

**Comment by Koooooo-7** [comment]
besides， fix the  [Sonar code smell](https://sonarcloud.io/project/issues?id=Koooooo-7_K-Bot&pullRequest=12&resolved=false&types=CODE_SMELL) also.  :wink:
